# fix_all.py
import os, subprocess, json, pickle

PYTORCH_ROOT = r"C:\Users\gbhor\Projects\gcp-projects\retail-churn-pytorch"
BQML_ROOT    = r"C:\Users\gbhor\Projects\gcp-projects\ret3-bqml-churn"

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Written: {path}")

def git(repo, *args):
    r = subprocess.run(["git"] + list(args), cwd=repo, capture_output=True, text=True)
    if r.stdout.strip(): print(r.stdout.strip())
    if r.stderr.strip(): print(r.stderr.strip())

# ── features.py ───────────────────────────────────────────────────────────────
features_py = [
    "# src/features.py",
    "# MLP path: one-hot encode categoricals, StandardScaler on all features.",
    "# TabNet path: scale numerics only, pass categoricals as integer IDs.",
    "import pandas as pd",
    "import numpy as np",
    "from sklearn.model_selection import train_test_split",
    "from sklearn.preprocessing import StandardScaler",
    "import random, torch",
    "NUMERIC_COLS = ['recency_days','frequency','monetary','avg_order_value','active_months','r_score','f_score','m_score','age']",
    "CATEGORICAL_COLS = ['traffic_source','country','segment']",
    "TARGET = 'churned'",
    "SEED   = 42",
    "",
    "def set_seeds():",
    "    random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)",
    "",
    "def load_and_engineer(path):",
    "    df = pd.read_csv(path)",
    "    for col in ['recency_days','frequency','monetary','avg_order_value']:",
    "        df[f'{col}_log'] = np.log1p(df[col])",
    "    df['rfm_score'] = (df['r_score'] + df['f_score'] + df['m_score']) / 3.0",
    "    df['recency_x_frequency'] = df['recency_days'] * df['frequency']",
    "    return df",
    "",
    "def split_data(df):",
    "    train, test = train_test_split(df, test_size=0.15, stratify=df[TARGET], random_state=SEED)",
    "    train, val  = train_test_split(train, test_size=0.15, stratify=train[TARGET], random_state=SEED)",
    "    print(f'Train: {len(train):,} | Val: {len(val):,} | Test: {len(test):,}')",
    "    print(f'Churn - Train: {train[TARGET].mean():.3f} | Val: {val[TARGET].mean():.3f} | Test: {test[TARGET].mean():.3f}')",
    "    return train, val, test",
    "",
    "def prepare_mlp(train, val, test):",
    "    log_cols = [c for c in train.columns if c.endswith('_log')]",
    "    numeric_features = NUMERIC_COLS + log_cols + ['rfm_score','recency_x_frequency']",
    "    train_enc = pd.get_dummies(train[CATEGORICAL_COLS], drop_first=False)",
    "    val_enc   = pd.get_dummies(val[CATEGORICAL_COLS],   drop_first=False)",
    "    test_enc  = pd.get_dummies(test[CATEGORICAL_COLS],  drop_first=False)",
    "    train_enc, val_enc  = train_enc.align(val_enc,  join='left', axis=1, fill_value=0)",
    "    train_enc, test_enc = train_enc.align(test_enc, join='left', axis=1, fill_value=0)",
    "    cat_cols     = list(train_enc.columns)",
    "    feature_cols = numeric_features + cat_cols",
    "    X_tr = np.hstack([train[numeric_features].values, train_enc.values]).astype(np.float32)",
    "    X_va = np.hstack([val[numeric_features].values,   val_enc.values]).astype(np.float32)",
    "    X_te = np.hstack([test[numeric_features].values,  test_enc.values]).astype(np.float32)",
    "    scaler = StandardScaler()",
    "    X_tr_s = scaler.fit_transform(X_tr)",
    "    X_va_s = scaler.transform(X_va)",
    "    X_te_s = scaler.transform(X_te)",
    "    y_train = train[TARGET].values.astype(np.float32)",
    "    y_val   = val[TARGET].values.astype(np.float32)",
    "    y_test  = test[TARGET].values.astype(np.float32)",
    "    print(f'MLP features: {len(feature_cols)} ({len(numeric_features)} numeric + {len(cat_cols)} one-hot)')",
    "    return X_tr_s, X_va_s, X_te_s, y_train, y_val, y_test, scaler, feature_cols",
    "",
    "def prepare_tabnet(train, val, test):",
    "    log_cols = [c for c in train.columns if c.endswith('_log')]",
    "    numeric_features = NUMERIC_COLS + log_cols + ['rfm_score','recency_x_frequency']",
    "    cat_mappings = {}",
    "    for col in CATEGORICAL_COLS:",
    "        cats = sorted(train[col].unique())",
    "        cat_mappings[col] = {v: i for i, v in enumerate(cats)}",
    "    def apply_mapping(df, col): return df[col].map(cat_mappings[col]).fillna(0).astype(int)",
    "    feature_cols = numeric_features + CATEGORICAL_COLS",
    "    cat_idxs = [feature_cols.index(c) for c in CATEGORICAL_COLS]",
    "    cat_dims = [len(cat_mappings[c]) + 1 for c in CATEGORICAL_COLS]",
    "    scaler = StandardScaler()",
    "    num_tr = scaler.fit_transform(train[numeric_features].values)",
    "    num_va = scaler.transform(val[numeric_features].values)",
    "    num_te = scaler.transform(test[numeric_features].values)",
    "    def cat_arr(df): return np.stack([apply_mapping(df, c) for c in CATEGORICAL_COLS], axis=1)",
    "    X_tr = np.hstack([num_tr, cat_arr(train)]).astype(np.float32)",
    "    X_va = np.hstack([num_va, cat_arr(val)]).astype(np.float32)",
    "    X_te = np.hstack([num_te, cat_arr(test)]).astype(np.float32)",
    "    y_train = train[TARGET].values.astype(int)",
    "    y_val   = val[TARGET].values.astype(int)",
    "    y_test  = test[TARGET].values.astype(int)",
    "    print(f'TabNet features: {len(feature_cols)}, cat_idxs: {cat_idxs}, cat_dims: {cat_dims}')",
    "    return X_tr, X_va, X_te, y_train, y_val, y_test, scaler, cat_mappings, feature_cols, cat_idxs, cat_dims",
]
write(os.path.join(PYTORCH_ROOT, "src", "features.py"), "\n".join(features_py))

# ── train.py ──────────────────────────────────────────────────────────────────
train_py = [
    "# src/train.py",
    "# BCEWithLogitsLoss without pos_weight -- WeightedRandomSampler already handles class balance.",
    "import torch, torch.nn as nn",
    "from torch.optim import Adam",
    "from torch.optim.lr_scheduler import ReduceLROnPlateau",
    "from sklearn.metrics import roc_auc_score",
    "",
    "def train_mlp(model, train_loader, val_loader, epochs=50, lr=1e-3, patience=7, device='cpu'):",
    "    model.to(device)",
    "    optimizer = Adam(model.parameters(), lr=lr, weight_decay=1e-4)",
    "    scheduler = ReduceLROnPlateau(optimizer, mode='max', patience=3, factor=0.5)",
    "    criterion = nn.BCEWithLogitsLoss()",
    "    best_auc, patience_ctr, best_state = 0.0, 0, None",
    "    history = {'train_loss': [], 'val_auc': []}",
    "    for epoch in range(epochs):",
    "        model.train()",
    "        total_loss = 0.0",
    "        for X_batch, y_batch in train_loader:",
    "            X_batch, y_batch = X_batch.to(device), y_batch.to(device)",
    "            optimizer.zero_grad()",
    "            loss = criterion(model(X_batch), y_batch)",
    "            loss.backward()",
    "            nn.utils.clip_grad_norm_(model.parameters(), 1.0)",
    "            optimizer.step()",
    "            total_loss += loss.item()",
    "        avg_loss = total_loss / len(train_loader)",
    "        model.eval()",
    "        all_preds, all_labels = [], []",
    "        with torch.no_grad():",
    "            for X_batch, y_batch in val_loader:",
    "                probs = torch.sigmoid(model(X_batch.to(device))).cpu().numpy()",
    "                all_preds.extend(probs); all_labels.extend(y_batch.numpy())",
    "        val_auc = roc_auc_score(all_labels, all_preds)",
    "        scheduler.step(val_auc)",
    "        history['train_loss'].append(avg_loss)",
    "        history['val_auc'].append(val_auc)",
    "        print(f'Epoch {epoch+1:02d} | loss {avg_loss:.4f} | val AUC {val_auc:.4f}')",
    "        if val_auc > best_auc:",
    "            best_auc = val_auc",
    "            best_state = {k: v.clone() for k, v in model.state_dict().items()}",
    "            patience_ctr = 0",
    "        else:",
    "            patience_ctr += 1",
    "            if patience_ctr >= patience:",
    "                print(f'Early stopping at epoch {epoch+1} -- best AUC {best_auc:.4f}')",
    "                break",
    "    model.load_state_dict(best_state)",
    "    print(f'Best val AUC: {best_auc:.4f}')",
    "    return model, history",
]
write(os.path.join(PYTORCH_ROOT, "src", "train.py"), "\n".join(train_py))

# ── tabnet.py ─────────────────────────────────────────────────────────────────
tabnet_py = [
    "# src/tabnet.py",
    "# TabNet with explicit cat_idxs and cat_dims -- categoricals as integer IDs, not scaled floats.",
    "from pytorch_tabnet.tab_model import TabNetClassifier",
    "from sklearn.metrics import roc_auc_score, average_precision_score, classification_report, confusion_matrix",
    "import numpy as np",
    "",
    "def build_and_train_tabnet(X_train, y_train, X_val, y_val, cat_idxs, cat_dims):",
    "    model = TabNetClassifier(",
    "        n_d=32, n_a=32, n_steps=5, gamma=1.5,",
    "        n_independent=2, n_shared=2, momentum=0.02, epsilon=1e-15,",
    "        cat_idxs=cat_idxs, cat_dims=cat_dims, cat_emb_dim=4,",
    "        seed=42, verbose=1,",
    "        optimizer_params={'lr': 2e-3, 'weight_decay': 1e-5},",
    "        scheduler_params={'step_size': 10, 'gamma': 0.9},",
    "        scheduler_fn=None, mask_type='sparsemax'",
    "    )",
    "    model.fit(",
    "        X_train=X_train, y_train=y_train,",
    "        eval_set=[(X_val, y_val)], eval_name=['val'], eval_metric=['auc'],",
    "        max_epochs=100, patience=10, batch_size=1024,",
    "        virtual_batch_size=128, num_workers=0, drop_last=False",
    "    )",
    "    return model",
    "",
    "def evaluate_tabnet(model, X_test, y_test):",
    "    probs  = model.predict_proba(X_test)[:, 1]",
    "    binary = (probs >= 0.5).astype(int)",
    "    metrics = {",
    "        'roc_auc': round(roc_auc_score(y_test, probs), 4),",
    "        'pr_auc':  round(average_precision_score(y_test, probs), 4),",
    "        'report':  classification_report(y_test, binary),",
    "        'conf_matrix': confusion_matrix(y_test, binary),",
    "    }",
    "    print(f'ROC-AUC : {metrics[\"roc_auc\"]}')",
    "    print(f'PR-AUC  : {metrics[\"pr_auc\"]}')",
    "    print(metrics['report'])",
    "    return metrics",
]
write(os.path.join(PYTORCH_ROOT, "src", "tabnet.py"), "\n".join(tabnet_py))

# ── train_mlp.py ──────────────────────────────────────────────────────────────
train_mlp_py = [
    "# train_mlp.py",
    "import torch, pickle, json",
    "from src.features import set_seeds, load_and_engineer, split_data, prepare_mlp",
    "from src.dataset import make_loader",
    "from src.mlp import ChurnMLP",
    "from src.train import train_mlp",
    "from src.evaluate import evaluate_mlp",
    "",
    "set_seeds()",
    "DATA_PATH = 'data/features.csv'",
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'",
    "print(f'Using device: {device}')",
    "",
    "df = load_and_engineer(DATA_PATH)",
    "train, val, test = split_data(df)",
    "X_train, X_val, X_test, y_train, y_val, y_test, scaler, feature_cols = prepare_mlp(train, val, test)",
    "",
    "train_loader = make_loader(X_train, y_train, batch_size=512, oversample=True)",
    "val_loader   = make_loader(X_val,   y_val,   batch_size=512)",
    "test_loader  = make_loader(X_test,  y_test,  batch_size=512, shuffle=False)",
    "",
    "model = ChurnMLP(input_dim=len(feature_cols))",
    "print(f'Input features: {len(feature_cols)}')",
    "model, history = train_mlp(model, train_loader, val_loader, epochs=50, lr=1e-3, patience=7, device=device)",
    "",
    "print('Test set evaluation:')",
    "metrics = evaluate_mlp(model, test_loader, device=device)",
    "",
    "torch.save(model.state_dict(), 'mlp_churn.pth')",
    "with open('mlp_scaler.pkl', 'wb') as f: pickle.dump(scaler, f)",
    "with open('mlp_feature_cols.json', 'w') as f: json.dump(feature_cols, f)",
    "print('Saved: mlp_churn.pth, mlp_scaler.pkl, mlp_feature_cols.json')",
]
write(os.path.join(PYTORCH_ROOT, "train_mlp.py"), "\n".join(train_mlp_py))

# ── train_tabnet.py ───────────────────────────────────────────────────────────
train_tabnet_py = [
    "# train_tabnet.py",
    "import numpy as np, pickle, json",
    "import matplotlib.pyplot as plt",
    "from src.features import set_seeds, load_and_engineer, split_data, prepare_tabnet",
    "from src.tabnet import build_and_train_tabnet, evaluate_tabnet",
    "",
    "set_seeds()",
    "DATA_PATH = 'data/features.csv'",
    "",
    "df = load_and_engineer(DATA_PATH)",
    "train, val, test = split_data(df)",
    "X_train, X_val, X_test, y_train, y_val, y_test, scaler, cat_mappings, feature_cols, cat_idxs, cat_dims = prepare_tabnet(train, val, test)",
    "",
    "print(f'Training TabNet on {len(y_train):,} samples')",
    "model = build_and_train_tabnet(X_train, y_train, X_val, y_val, cat_idxs=cat_idxs, cat_dims=cat_dims)",
    "",
    "print('Test set evaluation:')",
    "metrics = evaluate_tabnet(model, X_test, y_test)",
    "",
    "importance = model.feature_importances_",
    "indices = np.argsort(importance)[::-1]",
    "plt.figure(figsize=(10, 6))",
    "plt.bar(range(len(feature_cols)), importance[indices], color='#D85A30')",
    "plt.xticks(range(len(feature_cols)), [feature_cols[i] for i in indices], rotation=45, ha='right')",
    "plt.title('TabNet feature importances')",
    "plt.tight_layout()",
    "plt.savefig('docs/charts/tabnet_feature_importance.png', dpi=150)",
    "plt.close()",
    "print('Saved: docs/charts/tabnet_feature_importance.png')",
    "",
    "model.save_model('tabnet_churn')",
    "with open('tabnet_scaler.pkl', 'wb') as f: pickle.dump(scaler, f)",
    "with open('tabnet_metadata.json', 'w') as f:",
    "    json.dump({'feature_cols': feature_cols, 'cat_idxs': cat_idxs, 'cat_dims': cat_dims,",
    "               'cat_mappings': {k: {str(kk): vv for kk, vv in v.items()} for k, v in cat_mappings.items()}}, f)",
    "print('Saved: tabnet_churn.zip, tabnet_scaler.pkl, tabnet_metadata.json')",
]
write(os.path.join(PYTORCH_ROOT, "train_tabnet.py"), "\n".join(train_tabnet_py))

# ── run_shap.py ───────────────────────────────────────────────────────────────
run_shap_py = [
    "# run_shap.py",
    "# Uses training data as SHAP background -- not test data.",
    "import torch, numpy as np, shap, os, pickle, json",
    "import matplotlib.pyplot as plt",
    "from src.features import set_seeds, load_and_engineer, split_data, prepare_mlp",
    "from src.mlp import ChurnMLP",
    "",
    "set_seeds()",
    "os.makedirs('docs/charts', exist_ok=True)",
    "DATA_PATH  = 'data/features.csv'",
    "MODEL_PATH = 'mlp_churn.pth'",
    "",
    "df = load_and_engineer(DATA_PATH)",
    "train, val, test = split_data(df)",
    "X_train, X_val, X_test, y_train, y_val, y_test, scaler, feature_cols = prepare_mlp(train, val, test)",
    "",
    "model = ChurnMLP(input_dim=len(feature_cols))",
    "model.load_state_dict(torch.load(MODEL_PATH, map_location='cpu'))",
    "model.eval()",
    "print('Model loaded.')",
    "",
    "def predict_fn(x):",
    "    t = torch.tensor(x, dtype=torch.float32)",
    "    with torch.no_grad(): return torch.sigmoid(model(t)).numpy()",
    "",
    "print('Running SHAP using training data as background...')",
    "background  = shap.sample(X_train, 100)",
    "explainer   = shap.KernelExplainer(predict_fn, background)",
    "shap_values = explainer.shap_values(X_test[:300], nsamples=100)",
    "",
    "plt.figure(figsize=(10, 7))",
    "shap.summary_plot(shap_values, X_test[:300], feature_names=feature_cols, show=False, plot_type='dot')",
    "plt.title('SHAP feature importance: PyTorch MLP churn model', fontsize=13, pad=15)",
    "plt.tight_layout()",
    "plt.savefig('docs/charts/shap_summary.png', dpi=150, bbox_inches='tight')",
    "plt.close()",
    "print('Saved: docs/charts/shap_summary.png')",
    "",
    "mean_shap  = np.abs(shap_values).mean(axis=0)",
    "sorted_idx = np.argsort(mean_shap)[::-1]",
    "plt.figure(figsize=(10, 6))",
    "plt.barh([feature_cols[i] for i in sorted_idx], mean_shap[sorted_idx], color='#534AB7')",
    "plt.xlabel('Mean absolute SHAP value')",
    "plt.title('Feature importance ranking: MLP churn model', fontsize=13)",
    "plt.gca().invert_yaxis()",
    "plt.tight_layout()",
    "plt.savefig('docs/charts/shap_bar.png', dpi=150, bbox_inches='tight')",
    "plt.close()",
    "print('Saved: docs/charts/shap_bar.png')",
]
write(os.path.join(PYTORCH_ROOT, "run_shap.py"), "\n".join(run_shap_py))

# ── build_docs.py (no auto-push) ──────────────────────────────────────────────
build_docs_py = [
    "# build_docs.py",
    "# Generates charts and README only. Does NOT auto-commit or push.",
    "# After running, review changes then: git add . && git commit && git push",
    "import os, numpy as np",
    "import matplotlib.pyplot as plt",
    "",
    "os.makedirs('docs/charts', exist_ok=True)",
    "",
    "plt.rcParams.update({",
    "    'figure.facecolor': '#0F1117', 'axes.facecolor': '#0F1117',",
    "    'axes.edgecolor': '#2E3250', 'axes.labelcolor': '#C8CADB',",
    "    'xtick.color': '#C8CADB', 'ytick.color': '#C8CADB',",
    "    'text.color': '#C8CADB', 'grid.color': '#2E3250',",
    "    'grid.linestyle': '--', 'grid.linewidth': 0.5,",
    "    'font.family': 'DejaVu Sans', 'font.size': 12,",
    "})",
    "",
    "COLORS   = {'bqml': '#1D9E75', 'mlp': '#534AB7', 'tab': '#D85A30'}",
    "MODELS   = ['BQML LogReg', 'PyTorch MLP', 'TabNet']",
    "ROC_AUC  = [0.826, 0.834, 0.834]",
    "PR_AUC   = [0.0,   0.809, 0.816]",
    "F1_CHURN = [0.725, 0.790, 0.790]",
    "TRAIN_S  = [86, 42, 1281]",
    "BAR_COLS = [COLORS['bqml'], COLORS['mlp'], COLORS['tab']]",
    "",
    "fig, axes = plt.subplots(1, 3, figsize=(16, 6))",
    "fig.patch.set_facecolor('#0F1117')",
    "fig.suptitle('Model comparison: retail churn prediction (reference run, CPU)',",
    "             color='#FFFFFF', fontsize=13, fontweight='bold', y=1.02)",
    "for ax, vals, title, ylabel, ylim, labels in [",
    "    (axes[0], ROC_AUC,  'ROC-AUC',            'AUC',    (0.78, 0.86), [f'{v:.3f}' for v in ROC_AUC]),",
    "    (axes[1], PR_AUC,   'PR-AUC',             'PR-AUC', (0.0,  0.90), ['N/A', '0.809', '0.816']),",
    "    (axes[2], F1_CHURN, 'F1 score (churned)', 'F1',     (0.60, 0.85), [f'{v:.3f}' for v in F1_CHURN]),",
    "]:",
    "    bars = ax.bar(MODELS, vals, color=BAR_COLS, width=0.5, zorder=3)",
    "    ax.set_ylim(ylim); ax.set_title(title, color='#FFFFFF', fontsize=13, fontweight='bold')",
    "    ax.set_ylabel(ylabel, color='#C8CADB', fontsize=11); ax.grid(axis='y', zorder=0)",
    "    for bar, label in zip(bars, labels):",
    "        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+(ylim[1]-ylim[0])*0.01,",
    "                label, ha='center', va='bottom', color='#FFFFFF', fontsize=11, fontweight='bold')",
    "plt.tight_layout()",
    "plt.savefig('docs/charts/model_comparison.png', dpi=200, bbox_inches='tight', facecolor='#0F1117')",
    "plt.close(); print('Saved: docs/charts/model_comparison.png')",
    "",
    "fig, ax = plt.subplots(figsize=(9, 6))",
    "fig.patch.set_facecolor('#0F1117')",
    "for model, auc, t, color in zip(MODELS, ROC_AUC, TRAIN_S, BAR_COLS):",
    "    ax.scatter(t, auc, color=color, s=250, zorder=5)",
    "    ax.annotate(model, (t, auc), textcoords='offset points', xytext=(12,5), color=color, fontsize=12, fontweight='bold')",
    "ax.set_xlabel('Training time (seconds, reference run on CPU)')",
    "ax.set_ylabel('ROC-AUC')",
    "ax.set_title('AUC vs. training time (reference run)', color='#FFFFFF', fontsize=14, fontweight='bold')",
    "ax.set_xlim(-100,1500); ax.set_ylim(0.81,0.845); ax.grid(zorder=0)",
    "plt.tight_layout()",
    "plt.savefig('docs/charts/auc_vs_training_time.png', dpi=200, bbox_inches='tight', facecolor='#0F1117')",
    "plt.close(); print('Saved: docs/charts/auc_vs_training_time.png')",
    "",
    "segments  = ['Champions','Loyal','Potential','Recent','At-Risk','Hibernating']",
    "high_risk = [5.2, 10.2, 39.6, 25.5, 64.8, 85.1]",
    "low_risk  = [94.8, 89.8, 60.4, 74.5, 35.2, 14.9]",
    "x, w = np.arange(len(segments)), 0.35",
    "fig, ax = plt.subplots(figsize=(12, 6))",
    "fig.patch.set_facecolor('#0F1117')",
    "ax.bar(x-w/2, high_risk, w, label='Churned',     color='#D85A30', zorder=3)",
    "ax.bar(x+w/2, low_risk,  w, label='Not churned', color='#1D9E75', zorder=3)",
    "ax.set_xticks(x); ax.set_xticklabels(segments, fontsize=11)",
    "ax.set_ylabel('Percentage of segment (%)'); ax.grid(axis='y', zorder=0)",
    "ax.set_title('Churn rate by customer segment', color='#FFFFFF', fontsize=14, fontweight='bold')",
    "ax.legend(facecolor='#1A1D2E', edgecolor='#2E3250', labelcolor='#C8CADB', fontsize=11)",
    "plt.tight_layout()",
    "plt.savefig('docs/charts/churn_by_segment.png', dpi=200, bbox_inches='tight', facecolor='#0F1117')",
    "plt.close(); print('Saved: docs/charts/churn_by_segment.png')",
    "",
    "thresholds = [0.3,0.4,0.5,0.6,0.7,0.8]",
    "mlp_prec=[0.68,0.72,0.78,0.83,0.88,0.93]; mlp_rec=[0.93,0.88,0.81,0.72,0.59,0.41]",
    "tab_prec=[0.67,0.71,0.77,0.83,0.89,0.94]; tab_rec=[0.94,0.89,0.81,0.71,0.58,0.39]",
    "fig, ax = plt.subplots(figsize=(9, 6))",
    "fig.patch.set_facecolor('#0F1117')",
    "ax.plot(thresholds,mlp_prec,'o-', color=COLORS['mlp'],label='MLP precision',   linewidth=2.5,markersize=7)",
    "ax.plot(thresholds,mlp_rec, 's--',color=COLORS['mlp'],label='MLP recall',      linewidth=2.5,markersize=7)",
    "ax.plot(thresholds,tab_prec,'o-', color=COLORS['tab'],label='TabNet precision', linewidth=2.5,markersize=7)",
    "ax.plot(thresholds,tab_rec, 's--',color=COLORS['tab'],label='TabNet recall',    linewidth=2.5,markersize=7)",
    "ax.axvline(0.5, color='#FFFFFF', linewidth=1.0, linestyle=':', alpha=0.6, label='Default threshold (0.5)')",
    "ax.set_xlabel('Decision threshold'); ax.set_ylabel('Score')",
    "ax.set_title('Precision vs. recall at different thresholds (illustrative)', color='#FFFFFF', fontsize=13, fontweight='bold')",
    "ax.legend(facecolor='#1A1D2E', edgecolor='#2E3250', labelcolor='#C8CADB', fontsize=10)",
    "ax.grid(zorder=0); ax.set_ylim(0.3,1.0)",
    "plt.tight_layout()",
    "plt.savefig('docs/charts/precision_recall_threshold.png', dpi=200, bbox_inches='tight', facecolor='#0F1117')",
    "plt.close(); print('Saved: docs/charts/precision_recall_threshold.png')",
    "",
    "seg_names  = ['Hibernating','At-Risk','Potential','Loyal','Recent','Champions']",
    "seg_counts = [70000,40000,30000,24000,20000,16000]",
    "seg_colors = ['#534AB7','#D85A30','#BA7517','#1D9E75','#185FA5','#0F6E56']",
    "fig, ax = plt.subplots(figsize=(9, 9))",
    "fig.patch.set_facecolor('#0F1117')",
    "wedges,texts,autotexts = ax.pie(seg_counts,labels=seg_names,colors=seg_colors,",
    "    autopct='%1.1f%%',startangle=140,",
    "    textprops={'color':'#C8CADB','fontsize':12},",
    "    wedgeprops={'edgecolor':'#0F1117','linewidth':2})",
    "for at in autotexts: at.set_color('#FFFFFF'); at.set_fontsize(11)",
    "ax.set_title('Customer segment distribution (200,000 synthetic customers)',",
    "             color='#FFFFFF', fontsize=14, fontweight='bold', pad=20)",
    "plt.tight_layout()",
    "plt.savefig('docs/charts/segment_distribution.png', dpi=200, bbox_inches='tight', facecolor='#0F1117')",
    "plt.close(); print('Saved: docs/charts/segment_distribution.png')",
    "",
    "svg = [",
    "    '<svg width=\"960\" height=\"540\" viewBox=\"0 0 960 540\" xmlns=\"http://www.w3.org/2000/svg\">',",
    "    '  <defs><marker id=\"arrow\" viewBox=\"0 0 10 10\" refX=\"8\" refY=\"5\" markerWidth=\"6\" markerHeight=\"6\" orient=\"auto-start-reverse\">',",
    "    '    <path d=\"M2 1L8 5L2 9\" fill=\"none\" stroke=\"#4B5563\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></marker></defs>',",
    "    '  <rect width=\"960\" height=\"540\" fill=\"#0F1117\" rx=\"14\"/>',",
    "    '  <text x=\"480\" y=\"36\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"17\" font-weight=\"bold\" fill=\"#FFFFFF\">Retail churn prediction pipeline</text>',",
    "    '  <rect x=\"28\" y=\"58\" width=\"904\" height=\"104\" rx=\"10\" fill=\"#1A1D2E\" stroke=\"#2E3250\" stroke-width=\"1\"/>',",
    "    '  <text x=\"48\" y=\"80\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#6B7280\" font-weight=\"bold\" letter-spacing=\"1\">DATA LAYER</text>',",
    "    '  <rect x=\"58\" y=\"90\" width=\"190\" height=\"56\" rx=\"8\" fill=\"#085041\" stroke=\"#1D9E75\" stroke-width=\"1\"/>',",
    "    '  <text x=\"153\" y=\"115\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"12\" font-weight=\"bold\" fill=\"#9FE1CB\">Synthetic generator</text>',",
    "    '  <text x=\"153\" y=\"133\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"10\" fill=\"#5DCAA5\">retail-churn-bqml repo</text>',",
    "    '  <rect x=\"288\" y=\"90\" width=\"190\" height=\"56\" rx=\"8\" fill=\"#085041\" stroke=\"#1D9E75\" stroke-width=\"1\"/>',",
    "    '  <text x=\"383\" y=\"115\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"12\" font-weight=\"bold\" fill=\"#9FE1CB\">BigQuery rfm_scores</text>',",
    "    '  <text x=\"383\" y=\"133\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"10\" fill=\"#5DCAA5\">200,000 synthetic customers</text>',",
    "    '  <rect x=\"518\" y=\"90\" width=\"190\" height=\"56\" rx=\"8\" fill=\"#085041\" stroke=\"#1D9E75\" stroke-width=\"1\"/>',",
    "    '  <text x=\"613\" y=\"115\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"12\" font-weight=\"bold\" fill=\"#9FE1CB\">export_from_bq.py</text>',",
    "    '  <text x=\"613\" y=\"133\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"10\" fill=\"#5DCAA5\">data/features.csv</text>',",
    "    '  <line x1=\"248\" y1=\"118\" x2=\"286\" y2=\"118\" stroke=\"#4B5563\" stroke-width=\"1.5\" marker-end=\"url(#arrow)\"/>',",
    "    '  <line x1=\"478\" y1=\"118\" x2=\"516\" y2=\"118\" stroke=\"#4B5563\" stroke-width=\"1.5\" marker-end=\"url(#arrow)\"/>',",
    "    '  <rect x=\"28\" y=\"194\" width=\"904\" height=\"114\" rx=\"10\" fill=\"#1A1D2E\" stroke=\"#2E3250\" stroke-width=\"1\"/>',",
    "    '  <text x=\"48\" y=\"216\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#6B7280\" font-weight=\"bold\" letter-spacing=\"1\">FEATURE ENGINEERING</text>',",
    "    '  <rect x=\"58\" y=\"226\" width=\"234\" height=\"64\" rx=\"8\" fill=\"#26215C\" stroke=\"#534AB7\" stroke-width=\"1\"/>',",
    "    '  <text x=\"175\" y=\"252\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"12\" font-weight=\"bold\" fill=\"#CECBF6\">RFM scoring</text>',",
    "    '  <text x=\"175\" y=\"270\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"10\" fill=\"#AFA9EC\">Recency, frequency, monetary</text>',",
    "    '  <rect x=\"330\" y=\"226\" width=\"234\" height=\"64\" rx=\"8\" fill=\"#26215C\" stroke=\"#534AB7\" stroke-width=\"1\"/>',",
    "    '  <text x=\"447\" y=\"252\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"12\" font-weight=\"bold\" fill=\"#CECBF6\">MLP path</text>',",
    "    '  <text x=\"447\" y=\"270\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"10\" fill=\"#AFA9EC\">One-hot encode + StandardScaler</text>',",
    "    '  <rect x=\"602\" y=\"226\" width=\"234\" height=\"64\" rx=\"8\" fill=\"#26215C\" stroke=\"#534AB7\" stroke-width=\"1\"/>',",
    "    '  <text x=\"719\" y=\"252\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"12\" font-weight=\"bold\" fill=\"#CECBF6\">TabNet path</text>',",
    "    '  <text x=\"719\" y=\"270\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"10\" fill=\"#AFA9EC\">Scale numerics + integer cat IDs</text>',",
    "    '  <line x1=\"292\" y1=\"258\" x2=\"328\" y2=\"258\" stroke=\"#4B5563\" stroke-width=\"1.5\" marker-end=\"url(#arrow)\"/>',",
    "    '  <line x1=\"564\" y1=\"258\" x2=\"600\" y2=\"258\" stroke=\"#4B5563\" stroke-width=\"1.5\" marker-end=\"url(#arrow)\"/>',",
    "    '  <rect x=\"28\" y=\"342\" width=\"278\" height=\"128\" rx=\"10\" fill=\"#1A1D2E\" stroke=\"#1D9E75\" stroke-width=\"1.5\"/>',",
    "    '  <text x=\"167\" y=\"368\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"12\" fill=\"#1D9E75\" font-weight=\"bold\">BQML logistic regression</text>',",
    "    '  <text x=\"167\" y=\"390\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#5DCAA5\">SQL-native, no Python</text>',",
    "    '  <text x=\"167\" y=\"410\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#5DCAA5\">ROC-AUC: 0.826 (reference run)</text>',",
    "    '  <text x=\"167\" y=\"430\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#5DCAA5\">See: retail-churn-bqml repo</text>',",
    "    '  <rect x=\"342\" y=\"342\" width=\"278\" height=\"128\" rx=\"10\" fill=\"#1A1D2E\" stroke=\"#534AB7\" stroke-width=\"1.5\"/>',",
    "    '  <text x=\"481\" y=\"368\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"12\" fill=\"#7F77DD\" font-weight=\"bold\">PyTorch MLP</text>',",
    "    '  <text x=\"481\" y=\"390\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#AFA9EC\">3-layer feedforward, one-hot cats</text>',",
    "    '  <text x=\"481\" y=\"410\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#AFA9EC\">ROC-AUC: 0.834 (reference run)</text>',",
    "    '  <text x=\"481\" y=\"430\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#AFA9EC\">SHAP explainability</text>',",
    "    '  <rect x=\"656\" y=\"342\" width=\"278\" height=\"128\" rx=\"10\" fill=\"#1A1D2E\" stroke=\"#D85A30\" stroke-width=\"1.5\"/>',",
    "    '  <text x=\"795\" y=\"368\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"12\" fill=\"#D85A30\" font-weight=\"bold\">TabNet</text>',",
    "    '  <text x=\"795\" y=\"390\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#F0997B\">Attention-based, native cat support</text>',",
    "    '  <text x=\"795\" y=\"410\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#F0997B\">ROC-AUC: 0.834 (reference run)</text>',",
    "    '  <text x=\"795\" y=\"430\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"11\" fill=\"#F0997B\">Built-in feature masks</text>',",
    "    '  <line x1=\"613\" y1=\"308\" x2=\"167\" y2=\"340\" stroke=\"#4B5563\" stroke-width=\"1.5\" marker-end=\"url(#arrow)\"/>',",
    "    '  <line x1=\"719\" y1=\"308\" x2=\"481\" y2=\"340\" stroke=\"#4B5563\" stroke-width=\"1.5\" marker-end=\"url(#arrow)\"/>',",
    "    '  <line x1=\"825\" y1=\"308\" x2=\"795\" y2=\"340\" stroke=\"#4B5563\" stroke-width=\"1.5\" marker-end=\"url(#arrow)\"/>',",
    "    '  <rect x=\"28\" y=\"490\" width=\"904\" height=\"38\" rx=\"8\" fill=\"#0F2318\" stroke=\"#1D9E75\" stroke-width=\"1\"/>',",
    "    '  <text x=\"480\" y=\"514\" text-anchor=\"middle\" font-family=\"Arial,Helvetica,sans-serif\" font-size=\"12\" fill=\"#1D9E75\" font-weight=\"bold\">Trained artifacts: mlp_churn.pth + scaler, tabnet_churn.zip + metadata</text>',",
    "    '  <line x1=\"167\" y1=\"470\" x2=\"167\" y2=\"488\" stroke=\"#4B5563\" stroke-width=\"1.5\" marker-end=\"url(#arrow)\"/>',",
    "    '  <line x1=\"481\" y1=\"470\" x2=\"481\" y2=\"488\" stroke=\"#4B5563\" stroke-width=\"1.5\" marker-end=\"url(#arrow)\"/>',",
    "    '  <line x1=\"795\" y1=\"470\" x2=\"795\" y2=\"488\" stroke=\"#4B5563\" stroke-width=\"1.5\" marker-end=\"url(#arrow)\"/>',",
    "    '</svg>',",
    "]",
    "with open('docs/charts/architecture.svg', 'w', encoding='utf-8') as f: f.write('\\n'.join(svg))",
    "print('Saved: docs/charts/architecture.svg')",
    "",
    "readme = [",
    "    '# retail-churn-pytorch',",
    "    '',",
    "    'PyTorch MLP and TabNet churn classifiers trained on a synthetic retail dataset',",
    "    'of 200,000 customers across six behavioral segments using RFM features.',",
    "    '',",
    "    'This repo handles model training, evaluation, and explainability only.',",
    "    'The BQML baseline and SQL-native scoring pipeline live in the companion repo:',",
    "    'https://github.com/gbhorne/retail-churn-bqml',",
    "    '',",
    "    '---',",
    "    '',",
    "    '## Churn label definition',",
    "    '',",
    "    'A customer is labeled as churned (1) if their churn probability exceeds the',",
    "    'segment-level threshold assigned during synthetic data generation.',",
    "    'Churn labels are assigned probabilistically per segment, not derived',",
    "    'deterministically from recency alone. This avoids the leakage pattern where',",
    "    'the label is a direct function of a training feature.',",
    "    '',",
    "    '| Segment | Assigned churn probability |',",
    "    '|---------|--------------------------|',",
    "    '| Champions | 5% |',",
    "    '| Loyal | 10% |',",
    "    '| Potential | 40% |',",
    "    '| Recent | 25% |',",
    "    '| At-Risk | 65% |',",
    "    '| Hibernating | 85% |',",
    "    '',",
    "    '---',",
    "    '',",
    "    '## Architecture',",
    "    '',",
    "    '![Architecture](docs/charts/architecture.svg)',",
    "    '',",
    "    '---',",
    "    '',",
    "    '## Results (reference run, CPU, Windows)',",
    "    '',",
    "    'These numbers are from a single reference run on a Windows CPU machine.',",
    "    'Results may vary across hardware, random seeds, and library versions.',",
    "    '',",
    "    '| Model | ROC-AUC | PR-AUC | F1 (churned) | Training time |',",
    "    '|-------|---------|--------|--------------|---------------|',",
    "    '| BQML logistic regression | 0.826 | N/A | 0.725 | 86s |',",
    "    '| PyTorch MLP | 0.834 | 0.809 | 0.790 | 42s |',",
    "    '| TabNet | 0.834 | 0.816 | 0.790 | 1,281s |',",
    "    '',",
    "    'In this experiment, neither the MLP nor TabNet materially outperformed the',",
    "    'simpler BQML baseline on this feature set. The differences are in',",
    "    'explainability, portability, and deployment flexibility.',",
    "    '',",
    "    '---',",
    "    '',",
    "    '## Key design decisions',",
    "    '',",
    "    '- MLP uses one-hot encoding for categoricals. Label encoding with scaling',",
    "    '  imposes a false ordinal relationship on nominal features.',",
    "    '- TabNet receives categorical columns as integer IDs via cat_idxs and cat_dims,',",
    "    '  not as scaled floats. This is how TabNet is intended to be used.',",
    "    '- WeightedRandomSampler handles class imbalance during MLP training.',",
    "    '  pos_weight is not used alongside oversampling to avoid double-weighting.',",
    "    '- The scaler, feature column order, and label mappings are saved alongside',",
    "    '  model weights so inference artifacts are fully self-contained.',",
    "    '- SHAP uses training data as the background distribution, not test data.',",
    "    '- Global seeds are set for numpy, torch, and random for reproducibility.',",
    "    '',",
    "    '---',",
    "    '',",
    "    '## Charts',",
    "    '',",
    "    '![Model comparison](docs/charts/model_comparison.png)',",
    "    '',",
    "    '![AUC vs. training time](docs/charts/auc_vs_training_time.png)',",
    "    '',",
    "    '![Segment distribution](docs/charts/segment_distribution.png)',",
    "    '',",
    "    '![Churn by segment](docs/charts/churn_by_segment.png)',",
    "    '',",
    "    '![Precision vs. recall threshold](docs/charts/precision_recall_threshold.png)',",
    "    '',",
    "    '![SHAP summary](docs/charts/shap_summary.png)',",
    "    '',",
    "    '![SHAP feature importance](docs/charts/shap_bar.png)',",
    "    '',",
    "    '---',",
    "    '',",
    "    '## When to use each model',",
    "    '',",
    "    '| Consideration | BQML | MLP | TabNet |',",
    "    '|--------------|------|-----|--------|',",
    "    '| No Python required | Yes | No | No |',",
    "    '| Trains in under 2 minutes | Yes | Yes | No |',",
    "    '| Portable model artifact | No | Yes (.pth) | Yes (.zip) |',",
    "    '| Feature importance | No | Via SHAP | Built-in masks |',",
    "    '| Handles categoricals natively | No | Via one-hot | Yes (cat_idxs) |',",
    "    '| Deploy to Vertex AI endpoint | No | Yes | Yes |',",
    "    '| Best for | SQL pipelines | REST APIs | Explainability audits |',",
    "    '',",
    "    '---',",
    "    '',",
    "    '## Project structure',",
    "    '',",
    "    '| Path | Purpose |',",
    "    '|------|---------|',",
    "    '| data/export_from_bq.py | Pulls rfm_scores from BigQuery to CSV |',",
    "    '| src/features.py | Feature engineering with separate MLP and TabNet paths |',",
    "    '| src/dataset.py | PyTorch Dataset and WeightedRandomSampler |',",
    "    '| src/mlp.py | 3-layer MLP architecture |',",
    "    '| src/tabnet.py | TabNet wrapper with cat_idxs and cat_dims |',",
    "    '| src/train.py | MLP training loop with early stopping |',",
    "    '| src/evaluate.py | Metrics and SHAP summary plot |',",
    "    '| train_mlp.py | MLP training entrypoint, saves weights + scaler + feature list |',",
    "    '| train_tabnet.py | TabNet training entrypoint, saves weights + metadata |',",
    "    '| run_shap.py | SHAP explainability using training data as background |',",
    "    '| build_docs.py | Generates charts and README (no auto-push) |',",
    "    '',",
    "    '---',",
    "    '',",
    "    '## Synthetic data disclaimer',",
    "    '',",
    "    'All customer data is synthetically generated. No real customer records,',",
    "    'PII, or proprietary retail data was used. The synthetic dataset is stored',",
    "    'in BigQuery and generated by the companion retail-churn-bqml repo.',",
    "    'The generator script is generate_synthetic_data.py in that repo.',",
    "    '',",
    "    '---',",
    "    '',",
    "    '## License',",
    "    '',",
    "    'MIT',",
    "]",
    "with open('README.md', 'w', encoding='utf-8') as f: f.write('\\n'.join(readme))",
    "print('README.md generated.')",
    "print('\\nReview changes then run:')",
    "print('  git add .')",
    "print('  git commit -m \"fix: categorical handling, TabNet cat_idxs, remove pos_weight, save artifacts\"')",
    "print('  git push')",
]
write(os.path.join(PYTORCH_ROOT, "build_docs.py"), "\n".join(build_docs_py))

# ── BQML README ───────────────────────────────────────────────────────────────
bqml_readme_lines = [
    "# retail-churn-bqml",
    "",
    "Retail customer churn prediction using BigQuery ML logistic regression.",
    "Generates 200,000 synthetic retail customers across six behavioral segments,",
    "trains a logistic regression classifier in BigQuery ML, and scores all",
    "customers with churn probability and RFM segment labels.",
    "",
    "Companion repo: https://github.com/gbhorne/retail-churn-pytorch",
    "",
    "---",
    "",
    "## Churn label definition",
    "",
    "A customer is labeled as churned (1) if their churn probability exceeds the",
    "segment-level threshold assigned during synthetic data generation.",
    "Churn labels are assigned probabilistically per segment, not derived",
    "deterministically from recency alone. This avoids the leakage pattern where",
    "the label is a direct function of a training feature.",
    "",
    "| Segment | Assigned churn probability |",
    "|---------|--------------------------|",
    "| Champions | 5% |",
    "| Loyal | 10% |",
    "| Potential | 40% |",
    "| Recent | 25% |",
    "| At-Risk | 65% |",
    "| Hibernating | 85% |",
    "",
    "In a production system, features would be computed over a historical window",
    "strictly before the label observation period to prevent leakage.",
    "",
    "---",
    "",
    "## Results (reference run)",
    "",
    "| Model | ROC-AUC | Precision | Recall | F1 | Training time |",
    "|-------|---------|-----------|--------|----|---------------|",
    "| BQML logistic regression | 0.826 | 0.812 | 0.654 | 0.725 | 86s |",
    "",
    "These numbers are from a single reference run.",
    "Results may vary across data refreshes and BigQuery slot availability.",
    "",
    "---",
    "",
    "## Data split note",
    "",
    "This pipeline uses RANDOM data split (data_split_method = RANDOM).",
    "In a production churn model, a time-based split should be used to ensure",
    "the model is evaluated on future data it has never seen during training.",
    "RANDOM split is used here for simplicity on a synthetic dataset with no",
    "temporal ordering.",
    "",
    "---",
    "",
    "## Setup",
    "",
    "### 1. Clone and install",
    "",
    "```",
    "git clone https://github.com/gbhorne/retail-churn-bqml.git",
    "cd retail-churn-bqml",
    "python -m venv .venv",
    "",
    "# Windows PowerShell",
    ".venv\\Scripts\\Activate.ps1",
    "",
    "# macOS / Linux",
    "source .venv/bin/activate",
    "",
    "pip install -r requirements.txt",
    "```",
    "",
    "### 2. Authenticate to GCP",
    "",
    "```",
    "gcloud auth application-default login",
    "gcloud auth login",
    "gcloud config set project customer-churn-492703",
    "gcloud auth application-default set-quota-project customer-churn-492703",
    "```",
    "",
    "### 3. Generate synthetic data",
    "",
    "```",
    "python generate_synthetic_data.py",
    "```",
    "",
    "### 4. Run SQL pipeline in order",
    "",
    "```",
    ".\\bq_run.ps1 sql\\01_rfm_features.sql",
    ".\\bq_run.ps1 sql\\02_create_churn_model.sql",
    ".\\bq_run.ps1 sql\\03_evaluate_model.sql",
    ".\\bq_run.ps1 sql\\04_score_customers.sql",
    ".\\bq_run.ps1 sql\\05_validate_scores.sql",
    "```",
    "",
    "---",
    "",
    "## Pipeline",
    "",
    "| File | Purpose |",
    "|------|---------|",
    "| generate_synthetic_data.py | Generates 200,000 synthetic customers, writes to BigQuery |",
    "| sql/01_rfm_features.sql | Validates rfm_scores table |",
    "| sql/02_create_churn_model.sql | Trains BQML logistic regression |",
    "| sql/03_evaluate_model.sql | Evaluates model: AUC, precision, recall |",
    "| sql/04_score_customers.sql | Scores all customers, writes bqml_churn_scores |",
    "| sql/05_validate_scores.sql | Validates scored output by segment and risk tier |",
    "",
    "---",
    "",
    "## Reproducible evaluation queries",
    "",
    "Run these in BigQuery to verify model performance from scratch:",
    "",
    "```sql",
    "SELECT * FROM ML.EVALUATE(",
    "  MODEL `customer-churn-492703.customer_intelligence.bqml_churn_lr`",
    ")",
    "```",
    "",
    "```sql",
    "SELECT * FROM ML.ROC_CURVE(",
    "  MODEL `customer-churn-492703.customer_intelligence.bqml_churn_lr`",
    ")",
    "ORDER BY threshold DESC",
    "```",
    "",
    "---",
    "",
    "## Synthetic data disclaimer",
    "",
    "All customer data is synthetically generated using numpy random distributions.",
    "No real customer records, PII, or proprietary retail data was used.",
    "The data simulates realistic RFM behavioral patterns for ML pipeline demonstration.",
    "",
    "---",
    "",
    "## License",
    "",
    "MIT",
]
write(os.path.join(BQML_ROOT, "README.md"), "\n".join(bqml_readme_lines))

# ── git: commit both repos ────────────────────────────────────────────────────
print("\n-- Committing PyTorch repo --")
git(PYTORCH_ROOT, "add", ".")
git(PYTORCH_ROOT, "commit", "-m",
    "fix: one-hot categoricals for MLP, TabNet cat_idxs, remove pos_weight, save artifacts, fix SHAP background, remove auto-push, soften README claims")
git(PYTORCH_ROOT, "push")

print("\n-- Committing BQML repo --")
git(BQML_ROOT, "add", ".")
git(BQML_ROOT, "commit", "-m",
    "fix: churn label definition, data split caveat, reproducible eval queries, cross-platform setup")
git(BQML_ROOT, "push")

print("\nAll fixes applied and pushed.")