# fix_docs.py
# Adds remaining documentation fixes to both repos.
# Adds metrics saving to training scripts.
# Run: python fix_docs.py

import os, subprocess, json

PYTORCH_ROOT = r"C:\Users\gbhor\Projects\gcp-projects\retail-churn-pytorch"
BQML_ROOT    = r"C:\Users\gbhor\Projects\gcp-projects\ret3-bqml-churn"

def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Written: {path}")

def git(repo, *args):
    r = subprocess.run(["git"] + list(args), cwd=repo, capture_output=True, text=True)
    if r.stdout.strip(): print(r.stdout.strip())
    if r.stderr.strip(): print(r.stderr.strip())

# ── train_mlp.py: save metrics to JSON ───────────────────────────────────────
write(os.path.join(PYTORCH_ROOT, "train_mlp.py"), [
    "# train_mlp.py",
    "import torch, pickle, json, time",
    "from src.features import set_seeds, load_and_engineer, split_data, prepare_mlp",
    "from src.dataset import make_loader",
    "from src.mlp import ChurnMLP",
    "from src.train import train_mlp",
    "from src.evaluate import evaluate_mlp",
    "",
    "set_seeds()",
    "DATA_PATH = 'data/features.csv'",
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'",
    "print(f'Using device: {device}')",
    "",
    "df = load_and_engineer(DATA_PATH)",
    "train, val, test = split_data(df)",
    "X_train, X_val, X_test, y_train, y_val, y_test, scaler, feature_cols = prepare_mlp(train, val, test)",
    "",
    "train_loader = make_loader(X_train, y_train, batch_size=512, oversample=True)",
    "val_loader   = make_loader(X_val,   y_val,   batch_size=512)",
    "test_loader  = make_loader(X_test,  y_test,  batch_size=512, shuffle=False)",
    "",
    "model = ChurnMLP(input_dim=len(feature_cols))",
    "print(f'Input features: {len(feature_cols)}')",
    "",
    "t0 = time.time()",
    "model, history = train_mlp(model, train_loader, val_loader, epochs=50, lr=1e-3, patience=7, device=device)",
    "train_seconds = round(time.time() - t0, 1)",
    "",
    "print('Test set evaluation:')",
    "metrics = evaluate_mlp(model, test_loader, device=device)",
    "",
    "torch.save(model.state_dict(), 'mlp_churn.pth')",
    "with open('mlp_scaler.pkl', 'wb') as f: pickle.dump(scaler, f)",
    "with open('mlp_feature_cols.json', 'w') as f: json.dump(feature_cols, f)",
    "",
    "results = {",
    "    'model': 'PyTorch MLP',",
    "    'roc_auc': metrics['roc_auc'],",
    "    'pr_auc':  metrics['pr_auc'],",
    "    'train_seconds': train_seconds,",
    "    'device': device,",
    "    'n_features': len(feature_cols),",
    "    'n_train': len(y_train),",
    "    'n_val':   len(y_val),",
    "    'n_test':  len(y_test),",
    "    'churn_rate_train': round(float(y_train.mean()), 4),",
    "}",
    "with open('mlp_results.json', 'w') as f: json.dump(results, f, indent=2)",
    "print(f'Saved: mlp_churn.pth, mlp_scaler.pkl, mlp_feature_cols.json, mlp_results.json')",
    "print(f'Training time: {train_seconds}s')",
])

# ── train_tabnet.py: save metrics to JSON ────────────────────────────────────
write(os.path.join(PYTORCH_ROOT, "train_tabnet.py"), [
    "# train_tabnet.py",
    "import numpy as np, pickle, json, time",
    "import matplotlib.pyplot as plt",
    "from src.features import set_seeds, load_and_engineer, split_data, prepare_tabnet",
    "from src.tabnet import build_and_train_tabnet, evaluate_tabnet",
    "",
    "set_seeds()",
    "DATA_PATH = 'data/features.csv'",
    "",
    "df = load_and_engineer(DATA_PATH)",
    "train, val, test = split_data(df)",
    "X_train, X_val, X_test, y_train, y_val, y_test, scaler, cat_mappings, feature_cols, cat_idxs, cat_dims = prepare_tabnet(train, val, test)",
    "",
    "print(f'Training TabNet on {len(y_train):,} samples')",
    "t0 = time.time()",
    "model = build_and_train_tabnet(X_train, y_train, X_val, y_val, cat_idxs=cat_idxs, cat_dims=cat_dims)",
    "train_seconds = round(time.time() - t0, 1)",
    "",
    "print('Test set evaluation:')",
    "metrics = evaluate_tabnet(model, X_test, y_test)",
    "",
    "importance = model.feature_importances_",
    "indices = np.argsort(importance)[::-1]",
    "plt.figure(figsize=(10, 6))",
    "plt.bar(range(len(feature_cols)), importance[indices], color='#D85A30')",
    "plt.xticks(range(len(feature_cols)), [feature_cols[i] for i in indices], rotation=45, ha='right')",
    "plt.title('TabNet feature importances')",
    "plt.tight_layout()",
    "import os; os.makedirs('docs/charts', exist_ok=True)",
    "plt.savefig('docs/charts/tabnet_feature_importance.png', dpi=150)",
    "plt.close()",
    "print('Saved: docs/charts/tabnet_feature_importance.png')",
    "",
    "model.save_model('tabnet_churn')",
    "with open('tabnet_scaler.pkl', 'wb') as f: pickle.dump(scaler, f)",
    "with open('tabnet_metadata.json', 'w') as f:",
    "    json.dump({'feature_cols': feature_cols, 'cat_idxs': cat_idxs, 'cat_dims': cat_dims,",
    "               'cat_mappings': {k: {str(kk): vv for kk, vv in v.items()} for k, v in cat_mappings.items()}}, f)",
    "",
    "results = {",
    "    'model': 'TabNet',",
    "    'roc_auc': metrics['roc_auc'],",
    "    'pr_auc':  metrics['pr_auc'],",
    "    'train_seconds': train_seconds,",
    "    'device': 'cpu',",
    "    'n_features': len(feature_cols),",
    "    'cat_idxs': cat_idxs,",
    "    'cat_dims': cat_dims,",
    "    'n_train': len(y_train),",
    "    'n_val':   len(y_val),",
    "    'n_test':  len(y_test),",
    "    'churn_rate_train': round(float(y_train.mean()), 4),",
    "}",
    "with open('tabnet_results.json', 'w') as f: json.dump(results, f, indent=2)",
    "print(f'Saved: tabnet_churn.zip, tabnet_scaler.pkl, tabnet_metadata.json, tabnet_results.json')",
    "print(f'Training time: {train_seconds}s')",
])

# ── PyTorch README ────────────────────────────────────────────────────────────
write(os.path.join(PYTORCH_ROOT, "README.md"), [
    "# retail-churn-pytorch",
    "",
    "PyTorch MLP and TabNet churn classifiers trained on a synthetic retail dataset",
    "of 200,000 customers across six behavioral segments using RFM features.",
    "",
    "This repo covers model training, evaluation, and explainability.",
    "The BQML baseline and SQL-native scoring pipeline live in the companion repo:",
    "https://github.com/gbhorne/retail-churn-bqml",
    "",
    "---",
    "",
    "## Churn label definition",
    "",
    "| Property | Value |",
    "|----------|-------|",
    "| Observation window | Full synthetic purchase history per customer |",
    "| Prediction horizon | N/A (synthetic labels assigned at generation time) |",
    "| Churn rule | Probabilistic per segment (see table below) |",
    "| Scoring timestamp | End of observation window |",
    "",
    "Churn labels are assigned probabilistically per segment during data generation,",
    "not derived deterministically from any single feature. This avoids the leakage",
    "pattern where recency_days directly determines the churn label.",
    "",
    "| Segment | Churn probability |",
    "|---------|------------------|",
    "| Champions | 5% |",
    "| Loyal | 10% |",
    "| Potential | 40% |",
    "| Recent | 25% |",
    "| At-Risk | 65% |",
    "| Hibernating | 85% |",
    "",
    "In a production deployment, churn would be defined as no purchase within",
    "a fixed horizon (e.g. 90 days) following a feature cutoff date, with",
    "features computed strictly before that cutoff.",
    "",
    "---",
    "",
    "## Experiment design",
    "",
    "All three models (BQML, MLP, TabNet) are trained on the same underlying",
    "dataset with the same feature definitions to ensure a fair comparison.",
    "",
    "| Property | Value |",
    "|----------|-------|",
    "| Dataset | 200,000 synthetic retail customers |",
    "| Features | 9 numeric + log-scaled variants + interaction terms + categoricals |",
    "| MLP categorical handling | One-hot encoding (no ordinal assumption) |",
    "| TabNet categorical handling | Integer IDs via cat_idxs and cat_dims |",
    "| Train split | 72.25% (stratified) |",
    "| Validation split | 12.75% (stratified) |",
    "| Test split | 15% (stratified) |",
    "| Split method | Random stratified (no temporal ordering in synthetic data) |",
    "| Random seed | 42 (fixed for numpy, torch, and Python random) |",
    "| Class balance | 53% churned, 47% not churned |",
    "| Class imbalance handling | WeightedRandomSampler for MLP, native for TabNet |",
    "",
    "Note: a random split is appropriate here because the synthetic dataset has",
    "no temporal ordering. In a production system with real transaction data,",
    "a time-based split must be used to prevent future data leaking into training.",
    "",
    "---",
    "",
    "## Architecture",
    "",
    "![Architecture](docs/charts/architecture.svg)",
    "",
    "---",
    "",
    "## Results (reference run, CPU, Windows)",
    "",
    "Results are saved to mlp_results.json and tabnet_results.json after each",
    "training run. The numbers below are from a single reference run.",
    "Results will vary across hardware, random seeds, and library versions.",
    "",
    "| Model | ROC-AUC | PR-AUC | F1 (churned) | Training time |",
    "|-------|---------|--------|--------------|---------------|",
    "| BQML logistic regression | 0.826 | N/A | 0.725 | 86s |",
    "| PyTorch MLP | 0.834 | 0.809 | 0.790 | 42s |",
    "| TabNet | 0.834 | 0.816 | 0.790 | 1,281s |",
    "",
    "In this experiment, neither the MLP nor TabNet materially outperformed the",
    "simpler BQML baseline on this feature set. The differences are in",
    "explainability, portability, and deployment flexibility.",
    "",
    "---",
    "",
    "## Cost comparison",
    "",
    "| Model | Infrastructure | Estimated training cost | Scoring mechanism |",
    "|-------|---------------|------------------------|-------------------|",
    "| BQML logistic regression | None (serverless) | Cents per TB processed | ML.PREDICT in SQL |",
    "| PyTorch MLP | CPU VM or local machine | VM cost per training hour | REST API endpoint |",
    "| TabNet | CPU VM (GPU recommended) | Higher VM cost, longer run | REST API endpoint |",
    "",
    "BQML has the lowest total cost of ownership for batch scoring workloads.",
    "PyTorch models are more appropriate when a REST API serving layer is required",
    "or when the model needs to be embedded in an application.",
    "",
    "---",
    "",
    "## Decision threshold guide",
    "",
    "The default classification threshold of 0.5 is not always the right business",
    "decision. Use the precision-recall chart to select a threshold based on",
    "campaign economics.",
    "",
    "| Churn probability | Risk tier | Recommended action |",
    "|-------------------|-----------|--------------------|",
    "| >= 0.80 | High | Immediate retention intervention, personalized outreach |",
    "| 0.60 to 0.79 | Medium-high | Proactive nurture campaign, targeted offer |",
    "| 0.40 to 0.59 | Medium | Engagement campaign, product recommendation |",
    "| < 0.40 | Low | No action or low-cost passive re-engagement |",
    "",
    "Breakeven threshold formula: campaign cost / expected recovered lifetime value.",
    "Example: $5 campaign cost, $80 recovered LTV = act on any customer above 0.063.",
    "",
    "---",
    "",
    "## Key design decisions",
    "",
    "- MLP uses one-hot encoding for categoricals. Label encoding with scaling",
    "  imposes a false ordinal relationship on nominal features.",
    "- TabNet receives categorical columns as integer IDs via cat_idxs and cat_dims,",
    "  not as scaled floats. This is how TabNet is designed to be used.",
    "- WeightedRandomSampler handles class imbalance during MLP training.",
    "  pos_weight is not used alongside oversampling to avoid double-weighting.",
    "- The scaler, feature column order, and label mappings are saved alongside",
    "  model weights so inference artifacts are fully self-contained.",
    "- SHAP uses training data as the background distribution, not test data.",
    "- Global seeds are set for numpy, torch, and random for reproducibility.",
    "- The segment feature is derived from RFM scores and may carry partial",
    "  signal overlap with the churn label. It is retained as a real-world",
    "  proxy for customer lifecycle stage but should be monitored for redundancy",
    "  in production feature selection.",
    "",
    "---",
    "",
    "## Charts",
    "",
    "![Model comparison](docs/charts/model_comparison.png)",
    "",
    "![AUC vs. training time](docs/charts/auc_vs_training_time.png)",
    "",
    "![Segment distribution](docs/charts/segment_distribution.png)",
    "",
    "![Churn by segment](docs/charts/churn_by_segment.png)",
    "",
    "![Precision vs. recall threshold](docs/charts/precision_recall_threshold.png)",
    "",
    "![SHAP summary](docs/charts/shap_summary.png)",
    "",
    "![SHAP feature importance](docs/charts/shap_bar.png)",
    "",
    "---",
    "",
    "## When to use each model",
    "",
    "| Consideration | BQML | MLP | TabNet |",
    "|--------------|------|-----|--------|",
    "| No Python required | Yes | No | No |",
    "| Trains in under 2 minutes | Yes | Yes | No |",
    "| Portable model artifact | No | Yes (.pth) | Yes (.zip) |",
    "| Feature importance | No | Via SHAP | Built-in masks |",
    "| Handles categoricals natively | No | Via one-hot | Yes (cat_idxs) |",
    "| Deploy to Vertex AI endpoint | No | Yes | Yes |",
    "| Lowest infrastructure cost | Yes | No | No |",
    "| Best for | SQL pipelines | REST APIs | Explainability audits |",
    "",
    "---",
    "",
    "## Project structure",
    "",
    "| Path | Purpose |",
    "|------|---------|",
    "| data/export_from_bq.py | Pulls rfm_scores from BigQuery to CSV |",
    "| src/features.py | Feature engineering with separate MLP and TabNet paths |",
    "| src/dataset.py | PyTorch Dataset and WeightedRandomSampler |",
    "| src/mlp.py | 3-layer MLP architecture |",
    "| src/tabnet.py | TabNet wrapper with cat_idxs and cat_dims |",
    "| src/train.py | MLP training loop with early stopping |",
    "| src/evaluate.py | Metrics and SHAP summary |",
    "| train_mlp.py | MLP training entrypoint, saves weights + scaler + metrics |",
    "| train_tabnet.py | TabNet training entrypoint, saves weights + metadata + metrics |",
    "| run_shap.py | SHAP explainability using training data as background |",
    "| build_docs.py | Generates charts and README (no auto-push) |",
    "| mlp_results.json | Saved MLP experiment results (generated at training time) |",
    "| tabnet_results.json | Saved TabNet experiment results (generated at training time) |",
    "",
    "---",
    "",
    "## Synthetic data disclaimer",
    "",
    "All customer data is synthetically generated. No real customer records,",
    "PII, or proprietary retail data was used. The synthetic dataset is stored",
    "in BigQuery and generated by the companion retail-churn-bqml repo.",
    "The generator script is generate_synthetic_data.py in that repo.",
    "",
    "---",
    "",
    "## License",
    "",
    "MIT",
])

# ── BQML README ───────────────────────────────────────────────────────────────
write(os.path.join(BQML_ROOT, "README.md"), [
    "# retail-churn-bqml",
    "",
    "Retail customer churn prediction using BigQuery ML logistic regression.",
    "Generates 200,000 synthetic retail customers across six behavioral segments,",
    "trains a logistic regression classifier entirely in SQL using BigQuery ML,",
    "and scores all customers with churn probability and RFM segment labels.",
    "",
    "Companion repo: https://github.com/gbhorne/retail-churn-pytorch",
    "",
    "---",
    "",
    "## Churn label definition",
    "",
    "| Property | Value |",
    "|----------|-------|",
    "| Observation window | Full synthetic purchase history per customer |",
    "| Prediction horizon | N/A (synthetic labels assigned at generation time) |",
    "| Churn rule | Probabilistic per segment (see table below) |",
    "| Scoring timestamp | End of observation window |",
    "",
    "Churn labels are assigned probabilistically per segment during synthetic",
    "data generation, not derived deterministically from any single feature.",
    "This avoids the leakage pattern where recency_days directly determines",
    "the churn label.",
    "",
    "| Segment | Churn probability |",
    "|---------|------------------|",
    "| Champions | 5% |",
    "| Loyal | 10% |",
    "| Potential | 40% |",
    "| Recent | 25% |",
    "| At-Risk | 65% |",
    "| Hibernating | 85% |",
    "",
    "In a production deployment, churn would be defined as no purchase within",
    "a fixed horizon (e.g. 90 days) after a feature cutoff date. Features must",
    "be computed strictly before that cutoff to prevent leakage:",
    "",
    "```sql",
    "-- Production pattern: enforce feature cutoff before label window",
    "-- feature_cutoff = label_date - 90 days",
    "-- All features computed from events WHERE event_date < feature_cutoff",
    "-- Churn label = no purchase between feature_cutoff and label_date",
    "WITH feature_cutoff AS (",
    "  SELECT DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY) AS cutoff",
    ")",
    "SELECT",
    "  user_id,",
    "  COUNT(DISTINCT order_id) AS frequency,",
    "  SUM(sale_price)          AS monetary",
    "FROM orders",
    "WHERE order_date < (SELECT cutoff FROM feature_cutoff)",
    "GROUP BY user_id",
    "```",
    "",
    "---",
    "",
    "## Results (reference run)",
    "",
    "| Model | ROC-AUC | Precision | Recall | F1 | Training time |",
    "|-------|---------|-----------|--------|----|---------------|",
    "| BQML logistic regression | 0.826 | 0.812 | 0.654 | 0.725 | 86s |",
    "",
    "Verify from scratch using the reproducible evaluation queries below.",
    "",
    "---",
    "",
    "## Data split note",
    "",
    "This pipeline uses RANDOM data split (data_split_method = RANDOM).",
    "In a production churn model with real transaction data, a time-based",
    "split must be used to ensure the model is evaluated on future data",
    "it has never seen during training:",
    "",
    "```sql",
    "-- Production pattern: time-based split",
    "-- Train on data before cutoff, evaluate on data after",
    "CREATE OR REPLACE MODEL `project.dataset.churn_model`",
    "OPTIONS(",
    "  model_type = 'LOGISTIC_REG',",
    "  data_split_method = 'CUSTOM',",
    "  data_split_col = 'is_eval'",
    ")",
    "AS SELECT",
    "  *,",
    "  IF(last_order_date >= '2024-01-01', TRUE, FALSE) AS is_eval",
    "FROM `project.dataset.rfm_scores`",
    "```",
    "",
    "RANDOM split is used here because the synthetic dataset has no temporal",
    "ordering that would make time-based splitting meaningful.",
    "",
    "---",
    "",
    "## Reproducible evaluation queries",
    "",
    "Run these in BigQuery to verify model performance from scratch:",
    "",
    "```sql",
    "SELECT * FROM ML.EVALUATE(",
    "  MODEL `customer-churn-492703.customer_intelligence.bqml_churn_lr`",
    ")",
    "```",
    "",
    "```sql",
    "SELECT * FROM ML.ROC_CURVE(",
    "  MODEL `customer-churn-492703.customer_intelligence.bqml_churn_lr`",
    ")",
    "ORDER BY threshold DESC",
    "```",
    "",
    "---",
    "",
    "## Cost profile",
    "",
    "| Component | Cost model |",
    "|-----------|-----------|",
    "| Data generation | One-time BigQuery load job, minimal cost |",
    "| Model training | BigQuery on-demand: billed per TB of training data scanned |",
    "| Batch scoring | ML.PREDICT billed per TB scanned |",
    "| Storage | rfm_scores ~6.7MB, bqml_churn_scores ~8MB, negligible cost |",
    "| Infrastructure | None (fully serverless) |",
    "",
    "BQML eliminates all infrastructure management. There are no VMs, containers,",
    "or serving layers to maintain. Scoring runs as a SQL query on a schedule.",
    "",
    "---",
    "",
    "## Setup",
    "",
    "### 1. Clone and install",
    "",
    "```",
    "git clone https://github.com/gbhorne/retail-churn-bqml.git",
    "cd retail-churn-bqml",
    "python -m venv .venv",
    "",
    "# Windows PowerShell",
    ".venv\\Scripts\\Activate.ps1",
    "",
    "# macOS / Linux",
    "source .venv/bin/activate",
    "",
    "pip install -r requirements.txt",
    "```",
    "",
    "### 2. Authenticate to GCP",
    "",
    "```",
    "gcloud auth application-default login",
    "gcloud auth login",
    "gcloud config set project customer-churn-492703",
    "gcloud auth application-default set-quota-project customer-churn-492703",
    "```",
    "",
    "### 3. Generate synthetic data",
    "",
    "```",
    "python generate_synthetic_data.py",
    "```",
    "",
    "### 4. Run SQL pipeline in order",
    "",
    "```",
    ".\\bq_run.ps1 sql\\01_rfm_features.sql",
    ".\\bq_run.ps1 sql\\02_create_churn_model.sql",
    ".\\bq_run.ps1 sql\\03_evaluate_model.sql",
    ".\\bq_run.ps1 sql\\04_score_customers.sql",
    ".\\bq_run.ps1 sql\\05_validate_scores.sql",
    "```",
    "",
    "---",
    "",
    "## Pipeline",
    "",
    "| File | Purpose |",
    "|------|---------|",
    "| generate_synthetic_data.py | Generates 200,000 synthetic customers, writes to BigQuery |",
    "| sql/01_rfm_features.sql | Validates rfm_scores table |",
    "| sql/02_create_churn_model.sql | Trains BQML logistic regression |",
    "| sql/03_evaluate_model.sql | Evaluates model: AUC, precision, recall |",
    "| sql/04_score_customers.sql | Scores all customers, writes bqml_churn_scores |",
    "| sql/05_validate_scores.sql | Validates scored output by segment and risk tier |",
    "",
    "---",
    "",
    "## Synthetic data disclaimer",
    "",
    "All customer data is synthetically generated using numpy random distributions.",
    "No real customer records, PII, or proprietary retail data was used.",
    "The data simulates realistic RFM behavioral patterns for ML pipeline demonstration.",
    "",
    "---",
    "",
    "## License",
    "",
    "MIT",
])

# ── git: commit both repos ────────────────────────────────────────────────────
print("\n-- Committing PyTorch repo --")
git(PYTORCH_ROOT, "add", ".")
git(PYTORCH_ROOT, "commit", "-m",
    "docs: add experiment design, churn definition, cost comparison, threshold guide, metrics JSON output")
git(PYTORCH_ROOT, "push", "origin", "HEAD:master")

print("\n-- Committing BQML repo --")
git(BQML_ROOT, "add", ".")
git(BQML_ROOT, "commit", "-m",
    "docs: add churn definition, leakage proof SQL, time-based split pattern, cost profile, reproducible eval queries")
git(BQML_ROOT, "push")

print("\nAll documentation fixes applied and pushed.")